export default {
  artistName: 'Selena Gomez',
  artistId: '1',
  albumId: '1',
  albumType: 'Revival(Deluxe)',
  type: 'Album',
  albumYear: '2015',
  totalSongs: '58 Plays',
  songs: [
    {
      img: 'profile1.png',
      title: 'Song 1',
      artist: 'John',
      duration: '4:53',
      src: 'https://hanzluo.s3-us-west-1.amazonaws.com/music/zhiya.mp3',
      trackId: '1',
    },
    {
      img: 'profile2.png',
      title: 'Song 2',
      artist: 'Kethrin',
      duration: '6:20',
      src: 'https://hanzluo.s3-us-west-1.amazonaws.com/music/ziyounvshen.mp3',
      trackId: '2',
    },
    {
      img: 'profile1.png',
      title: 'Song 3',
      artist: 'Kethrin',
      duration: '3:20',
      src: 'https://hanzluo.s3-us-west-1.amazonaws.com/music/wuyuwuqing.mp3',
      trackId: '3',
    },
    {
      img: 'profile2.png',
      title: 'Song 4',
      artist: 'Kethrin',
      duration: '4:20',
      src: 'https://hanzluo.s3-us-west-1.amazonaws.com/music/suipian.mp3',
      trackId: '4',
    },
    {
      img: 'profile1.png',
      title: 'Song 5',
      artist: 'Kethrin',
      duration: '5:20',
      src:
        'https://hanzluo.s3-us-west-1.amazonaws.com/music/yonghengdegangwan.mp3',
      trackId: '5',
    },
  ],
};
