export default {
  artistName: 'Selena Gomez',
  artistId: '1',
  albumId: '1',
  albumType: 'Revival(Deluxe)',
  type: 'Album',
  albumYear: '2015',
  totalSongs: '58 Plays',
  songs: [
    {
      img: 'profile1.png',
      title: 'Walking Promises',
      artist: 'John',
      duration: '4:53',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      trackId: '1',
    },
    {
      img: 'profile2.png',
      title: 'Walking Promises',
      artist: 'Anna Ellison, Claire',
      duration: '6:20',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      trackId: '2',
    },
    {
      img: 'profile1.png',
      title: 'Walking Promises',
      artist: 'Anna Ellison, Claire',
      duration: '3:20',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      trackId: '3',
    },
    {
      img: 'profile2.png',
      title: 'Walking Promises',
      artist: 'Anna Ellison, Claire',
      duration: '4:20',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      trackId: '4',
    },
    {
      img: 'profile1.png',
      title: 'Walking Promises',
      artist: 'Anna Ellison, Claire',
      duration: '5:20',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      trackId: '5',
    },
    {
      img: 'profile1.png',
      title: 'Walking Promises',
      artist: 'Anna Ellison, Claire',
      duration: '5:20',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      trackId: '5',
    },
    {
      img: 'profile1.png',
      title: 'Walking Promises',
      artist: 'Anna Ellison, Claire',
      duration: '5:20',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      trackId: '5',
    },
    {
      img: 'profile1.png',
      title: 'Walking Promises',
      artist: 'Anna Ellison, Claire',
      duration: '5:20',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      trackId: '5',
    },
    {
      img: 'profile1.png',
      title: 'Walking Promises',
      artist: 'Anna Ellison, Claire',
      duration: '5:20',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      trackId: '5',
    },
    {
      img: 'profile1.png',
      title: 'Walking Promises',
      artist: 'Anna Ellison, Claire',
      duration: '5:20',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      trackId: '5',
    },
    {
      img: 'profile1.png',
      title: 'Walking Promises',
      artist: 'Anna Ellison, Claire',
      duration: '5:20',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      trackId: '5',
    },
    {
      img: 'profile1.png',
      title: 'Walking Promises',
      artist: 'Anna Ellison, Claire',
      duration: '5:20',
      src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      trackId: '5',
    },
  ],
};
