/*
 *
 * Influencer constants
 *
 */

export const BECOME_AN_INFLUENCER = 'app/Influencer/BECOME_AN_INFLUENCER';
export const BECOME_AN_INFLUENCER_SUCCESS =
  'app/Influencer/BECOME_AN_INFLUENCER_SUCCESS';
export const BECOME_AN_INFLUENCER_FAIL =
  'app/Influencer/BECOME_AN_INFLUENCER_FAIL';

export const GET_SOCIAL_CHANNELS = 'app/Influencer/GET_SOCIAL_CHANNELS';
export const GET_SOCIAL_CHANNELS_SUCCESS =
  'app/Influencer/GET_SOCIAL_CHANNELS_SUCCESS';
export const GET_SOCIAL_CHANNELS_FAIL =
  'app/Influencer/GET_SOCIAL_CHANNELS_FAIL';

export const GET_GENRES = 'app/Influencer/GET_GENRES';
export const GET_GENRES_SUCCESS = 'app/Influencer/GET_GENRES_SUCCESS';
export const GET_GENRES_FAIL = 'app/Influencer/GET_GENRES_FAIL';

export const GET_INFLUENCER_PROFILE = 'app/Influencer/GET_INFLUENCER_PROFILE';
export const GET_INFLUENCER_PROFILE_SUCCESS =
  'app/Influencer/GET_INFLUENCER_PROFILE_SUCCESS';
export const GET_INFLUENCER_PROFILE_FAIL =
  'app/Influencer/GET_INFLUENCER_PROFILE_FAIL';

export const GET_INFLUENCER_REQUESTS = 'app/Influencer/GET_INFLUENCER_REQUESTS';
export const GET_INFLUENCER_REQUESTS_SUCCESS =
  'app/Influencer/GET_INFLUENCER_REQUESTS_SUCCESS';
export const GET_INFLUENCER_REQUESTS_FAIL =
  'app/Influencer/GET_INFLUENCER_REQUESTS_FAIL';

export const UPDATE_INFLUENCER_STATUS_REQUEST =
  'app/Influencer/UPDATE_INFLUENCER_STATUS_REQUEST';
export const UPDATE_INFLUENCER_STATUS_SUCCESS =
  'app/Influencer/UPDATE_INFLUENCER_STATUS_SUCCESS';
export const UPDATE_INFLUENCER_STATUS_FAIL =
  'app/Influencer/UPDATE_INFLUENCER_STATUS_FAIL';
export const FETCH_INFLUENCER_STATS = 'app/Influencer/FETCH_INFLUENCER_STATS'
export const SAVE_INFLUENCER_STATS = 'app/Influencer/SAVE_INFLUENCER_STATS'