export const FETCH_TEAMS = 'app/Team/FETCH_TEAMS';
export const SAVE_TEAMS = 'app/Team/SAVE_TEAMS';
export const FETCH_TEAMS_ERROR = 'app/Team/FETCH_TEAMS_ERROR';
export const SHOW_PROGRESS = 'app/Team/SHOW_PROGRESS';
export const ADD_TEAM = 'app/Team/ADD_TEAM';

export const FETCH_TEAM_DETAILS = 'app/Team/FETCH_TEAM_DETAILS';
export const SAVE_TEAM_DETAILS = 'app/Team/SAVE_TEAM_DETAILS';

export const  SAVE_TEAM_NAME = 'app/Team/SAVE_TEAM_NAME';
export const  SAVE_TEAM_NAME_SUCCESS = 'app/Team/SAVE_TEAM_NAME_SUCCESS';
export const  SAVE_TEAM_NAME_ERROR = 'app/Team/SAVE_TEAM_NAME_ERROR';

export const SAVE_TEAM_MEMBER = 'app/TEAM/SAVE_TEAM_MEMBER';
export const SAVE_TEAM_MEMBER_SUCCESS = 'app/TEAM/SAVE_TEAM_MEMBER_SUCCESS';
export const SAVE_TEAM_MEMBER_ERROR = 'app/TEAM/SAVE_TEAM_MEMBER_ERROR';

export const FETCH_PENDING_INVITES = 'app/TEAM/FETCH_PENDING_INVITES';
export const SAVE_PENDING_INVITES = 'app/TEAM/SAVE_PENDING_INVITES';

export const CANCEL_PENDING_REQUEST = 'app/TEAM/CANCEL_PENDING_REQUEST';

export const FETCH_TEAM_MEMBERS = 'app/TEAM/FETCH_TEAM_MEMBERS';
export const SAVE_TEAM_MEMBERS = 'app/TEAM/SAVE_TEAM_MEMBERS';

export const FETCH_MY_TEAM_REQUESTS = 'app/TEAM/FETCH_MY_TEAM_REQUESTS';
export const SAVE_MY_TEAM_REQUESTS = 'app/TEAM/SAVE_MY_TEAM_REQUESTS';

export const REQUEST_ACTION = 'app/TEAM/REQUEST_ACTION';
