export const REQUEST_INFLUENCER = 'app/Account/REQUEST_INFLUENCER';
export const FETCH_ACTIVITY = 'app/Account/FETCH_ACTIVITY';
export const PUT_ACTIVITIES = 'app/Account/PUT_ACTIVITIES';
export const PUT_REVIEWS = 'app/Account/PUT_REVIEWS';
export const PUT_RATINGS = 'app/Account/PUT_RATINGS';
export const UPDATE_USER_DETAILS = 'app/Account/UPDATE_USER_DETAILS';
export const UPDATE_REGULAR_USER_DETAILS = 'app/Account/UPDATE_REGULAR_USER_DETAILS';
export const UPDATE_INFLUENCER_DETAILS =
  'app/Account/UPDATE_INFLUENCER_DETAILS';
export const UPDATE_PROCESSING = 'app/Account/UPDATE_PROCESSING';
export const UPDATE_INFLUENCER_PROCESSING =
  'app/Account/UPDATE_INFLUENCER_PROCESSING';

  export const FETCH_USERS_COUNTRIES = 'app/Account/FETCH_USERS_COUNTRIES';
  export const SAVE_USERS_COUNTRIES = 'app/Account/SAVE_USERS_COUNTRIES';