/*
 *
 * Song constants
 *
 */

export const GET_SONGS_REQUEST = 'app/Song/GET_SONGS_REQUEST';
export const GET_SONGS_REQUEST_SUCCESS = 'app/Song/GET_SONGS_REQUEST_SUCCESS';
export const GET_SONGS_REQUEST_FAIL = 'app/Song/GET_SONGS_REQUEST_FAIL';
export const UPLOAD_SONG_REQUEST = 'app/Song/UPLOAD_SONG_REQUEST';
export const UPLOAD_SONG_SUCCESS = 'app/Song/UPLOAD_SONG_SUCCESS';
export const UPLOAD_SONG_FAILURE = 'app/Song/UPLOAD_SONG_FAILURE';
export const DELETE_SONG = 'app/Song/DELETE_SONG';
export const DELETE_SONG_SUCCESS = 'app/Song/DELETE_SONG_SUCCESS';
export const DELETE_SONG_FAILURE = 'app/Song/DELETE_SONG_FAILURE';
export const GET_SONG_REQUEST = 'app/Song/GET_SONG_REQUEST';
export const GET_SONG_REQUEST_SUCCESS = 'app/Song/GET_SONG_REQUEST_SUCCESS';
export const GET_SONG_REQUEST_FAIL = 'app/Song/GET_SONG_REQUEST_FAIL';
export const POST_SONG_REQUEST = 'app/Song/POST_SONG_REQUEST';
export const POST_SONG_REQUEST_SUCCESS = 'app/Song/POST_SONG_REQUEST_SUCCESS';
export const POST_SONG_REQUEST_FAIL = 'app/Song/POST_SONG_REQUEST_FAIL';
export const UPDATE_SONG_REQUEST = 'app/Song/UPDATE_SONG_REQUEST';
export const UPDATE_SONG_REQUEST_SUCCESS =
  'app/Song/UPDATE_SONG_REQUEST_SUCCESS';
export const UPDATE_SONG_REQUEST_FAIL = 'app/Song/UPDATE_SONG_REQUEST_FAIL';
export const GET_GENRES = 'app/Song/GET_GENRES';
export const GET_GENRES_SUCCESS = 'app/Song/GET_GENRES_SUCCESS';
export const GET_GENRES_FAIL = 'app/Song/GET_GENRES_FAIL';

export const GET_MOOD_LIST = 'app/Song/GET_MOOD_LIST';
export const SAVE_MOOD_LIST = 'app/Song/SAVE_MOOD_LIST';