/*
 *
 * Earnings constants
 *
 */

export const GET_SONGS_STATS = 'app/Earnings/GET_SONGS_STATS';
export const GET_SONGS_STATS_SUCCESS = 'app/Earnings/GET_SONGS_STATS_SUCCESS';
export const GET_SONGS_STATS_FAILURE = 'app/Earnings/GET_SONGS_STATS_FAILURE';

export const GET_MY_SUPPORTED_ARTISTS = 'app/Earnings/GET_MY_SUPPORTED_ARTISTS';
export const GET_MY_SUPPORTED_ARTISTS_SUCCESS = 'app/Earnings/GET_MY_SUPPORTED_ARTISTS_SUCCESS';
export const GET_MY_SUPPORTED_ARTISTS_FAILURE = 'app/Earnings/GET_MY_SUPPORTED_ARTISTS_FAILURE';

export const GET_PER_STREAM_COST = 'app/Earnings/GET_PER_STREAM_COST';
export const GET_PER_STREAM_COST_SUCCESS = 'app/Earnings/GET_PER_STREAM_COST_SUCCESS';
export const GET_PER_STREAM_COST_FAILURE = 'app/Earnings/GET_PER_STREAM_COST_FAILURE';

export const GET_USER_CENTRIC_COST = 'app/Earnings/GET_USER_CENTRIC_COST';
export const GET_USER_CENTRIC_COST_SUCCESS = 'app/Earnings/GET_USER_CENTRIC_COST_SUCCESS';
export const GET_USER_CENTRIC_COST_FAILURE = 'app/Earnings/GET_USER_CENTRIC_COST_FAILURE';
