/*
 *
 * Auth constants
 *
 */
export const LOGIN_REQ = 'app/Auth/LOGIN_REQ';
export const LOGIN_SUCCESS = 'app/Auth/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'app/Auth/LOGIN_FAIL';

export const REGISTER_REQ = 'app/Auth/REGISTER_REQ';
export const REGISTER_SUCCESS = 'app/Auth/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'app/Auth/REGISTER_FAIL';

export const VERIFICATION_REQUEST = 'app/Auth/VERIFICATION_REQUEST';
export const VERIFICATION_REQUEST_SUCCESS =
  'app/Auth/VERIFICATION_REQUEST_SUCCESS';
export const VERIFICATION_REQUEST_FAIL = 'app/Auth/VERIFICATION_REQUEST_FAIL';

export const FORGOT_PASSWORD_REQUEST = 'app/Auth/FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_REQUEST_SUCCESS =
  'app/Auth/FORGOT_PASSWORD_REQUEST_SUCCESS';
export const FORGOT_PASSWORD_REQUEST_FAIL = 'app/Auth/FORGOT_PASSWORD_REQUEST_FAIL';

export const RESET_PASSWORD_REQUEST = 'app/Auth/RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_REQUEST_SUCCESS =
  'app/Auth/RESET_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST_FAIL = 'app/Auth/RESET_PASSWORD_REQUEST_FAIL';
