/*
 *
 * Playlist constants
 *
 */

export const CREATE_PLAYLIST_REQUEST = 'app/Playlist/CREATE_PLAYLIST_REQUEST';
export const CREATE_PLAYLIST_SUCCESS = 'app/Playlist/CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_FAIL = 'app/Playlist/CREATE_PLAYLIST_FAIL';

export const UPDATE_PLAYLIST_REQUEST = 'app/Playlist/UPDATE_PLAYLIST_REQUEST';
export const UPDATE_PLAYLIST_SUCCESS = 'app/Playlist/UPDATE_PLAYLIST_SUCCESS';
export const UPDATE_PLAYLIST_FAIL = 'app/Playlist/UPDATE_PLAYLIST_FAIL';

export const GET_PLAYLIST_REQUEST = 'app/Playlist/GET_PLAYLIST_REQUEST';
export const GET_PLAYLIST_SUCCESS = 'app/Playlist/GET_PLAYLIST_SUCCESS';
export const GET_PLAYLIST_FAIL = 'app/Playlist/GET_PLAYLIST_FAIL';

export const GET_MY_PLAYLISTS_REQUEST = 'app/Playlist/GET_MY_PLAYLISTS_REQUEST';
export const GET_MY_PLAYLISTS_SUCCESS = 'app/Playlist/GET_MY_PLAYLISTS_SUCCESS';
export const GET_MY_PLAYLISTS_FAIL = 'app/Playlist/GET_MY_PLAYLISTS_FAIL';

export const DELETE_PLAYLIST_REQUEST = 'app/Playlist/DELETE_PLAYLIST_REQUEST';
export const DELETE_PLAYLIST_SUCCESS = 'app/Playlist/DELETE_PLAYLIST_SUCCESS';
export const DELETE_PLAYLIST_FAIL = 'app/Playlist/DELETE_PLAYLIST_FAIL';

export const TOGGLE_PLAYLIST_POPUP = 'app/Playlist/TOGGLE_PLAYLIST_POPUP';
export const TOGGLE_UPDATE_PLAYLIST_POPUP = 'app/Playlist/TOGGLE_UPDATE_PLAYLIST_POPUP';

export const DELETE_SONG_PLAYLIST_REQUEST =
  'app/Playlist/DELETE_SONG_PLAYLIST_REQUEST';
export const DELETE_SONG_PLAYLIST_SUCCESS =
  'app/Playlist/DELETE_SONG_PLAYLIST_SUCCESS';
export const DELETE_SONG_PLAYLIST_FAIL =
  'app/Playlist/DELETE_SONG_PLAYLIST_FAIL';

export const ADD_SONG_INTO_PAYLIST = 'app/Playlist/ADD_SONG_INTO_PAYLIST';
export const ADD_SONG_INTO_PAYLIST_SUCCESS =
  'app/Playlist/ADD_SONG_INTO_PAYLIST_SUCCESS';
export const ADD_SONG_INTO_PAYLIST_FAIL =
  'app/Playlist/ADD_SONG_INTO_PAYLIST_FAIL';

export const CREATE_PLAYLIST_AND_ADD_SONG =
  'app/Playlist/CREATE_PLAYLIST_AND_ADD_SONG';
export const CREATE_PLAYLIST_AND_ADD_SONG_SUCCESS =
  'app/Playlist/CREATE_PLAYLIST_AND_ADD_SONG_SUCCESS';
export const CREATE_PLAYLIST_AND_ADD_SONG_FAIL =
  'app/Playlist/CREATE_PLAYLIST_AND_ADD_SONG_FAIL';

  export const FOLLOW_PLAYLIST = 'app/playlist/FOLLOW_PLAYLIST';